### PR TITLE
ROO-3639: add renderLabel attribute in form fields tags

### PR DESCRIPTION
**Pull request by thepins**
Update form fields tags datetime, display, editor, input, select, simple, textarea to add renderLabel directive. This directive indicate if the contents of the label should be rendered.

renderLabel default value is true
When renderLabel is false, the label is hide

### CODE REVIEW

**Comment by jmvivo** [comment]
Please complete the online individual contributers agreement at https://support.springsource.com/spring_committer_signup so I can apply your patch.

**Comment by thepins** [comment]
Hy,

It's ok i have complete the individual agreement.

**Comment by jcagarcia** [comment]
I've just created the following JIRA task related with your improvement:

https://jira.spring.io/browse/ROO-3639

**Comment by jcagarcia** [comment]
Hi @thepins,

I've been looking your proposal... and I think that is a great idea!!!

I have only one comment, if you set "renderLabel" attribute to false, you lost the distribution of the form:


 that you could apply easily:

**Comment by jcagarcia** [comment]
Hi @thepins,

I've been looking your proposal... and I think that is a great idea!!!

I have only one comment, if you set "renderLabel" attribute to false, you lost the distribution of the form:

Form distribution

You could solve it easily applying the following solution on every tagx:

````
         <label for="_${sec_field}_id">
          <c:choose>
            <c:when test="${empty renderLabel or renderLabel}">
              <c:out value="${label}" />
            :
            </c:when>
            <c:otherwise>
              &amp;nbsp;
            </c:otherwise>
          </c:choose>
        </label>
````

Form distribution with solution

Apply the changes above on this pull-request and I will accept it! ;)

Regards,

**Comment by thepins** [comment]
Hy @jcagarcia ,

Ok, thanks. I will apply this solution soon.

David

**Comment by thepins** [comment]
I applied the changes and tested with blank roo project

**Comment by jcagarcia** [comment]
Thanks for your contribution!!!! :D 

Cheers,

**Pull request merged**
